env: production
description: &description "Technical blog by backend developer Junghoon Ban."
author: junghoon-vans

defaultTheme: auto
displayFullLangName: true
ShowReadingTime: true
ShowWordCount: true
ShowBreadCrumbs: true
ShowPostNavLinks: true
ShowCodeCopyButtons: true
ShowShareButtons: true
ShowAllPagesInArchive: true
ShowPageNums: true
ShowRssButtonInSectionTermList: true
showtoc: true
UseHugoToc: true
comments: true

fuseOpts:
  isCaseSensitive: false
  shouldSort: true
  threshold: 0.4
  distance: 100
  ignoreLocation: true
  minMatchCharLength: 2
  limit: 10
  keys:
    - title
    - permalink
    - summary
    - content

homeInfoParams:
  Title: "Hello World!"
  Content: *description

socialIcons:
  - name: github
    url: "https://github.com/junghoon-vans"
  - name: X
    url: "https://x.com/vans_x96"
  - name: linkedin
    url: "https://www.linkedin.com/in/junghoon-ban"
  - name: email
    url: "mailto:junghoon.ban@gmail.com"

editPost:
  URL: "https://github.com/junghoon-vans/vanslog/tree/main/content"
  Text: "수정"
  appendFilePath: true
